# Codemods CI Build

name: Codemods CI Build

on:
  pull_request:
    branches:
      - main

jobs:
  extract-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: npm install
        run: npm install

      - name: npm test
        run: npm run test