# Codemods CI Build

name: Codemods CI Build

on:
  pull_request:
    branches:
      - main

jobs:
  ci-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: npm install
        run: npm install

      - name: npm test
        run: npm run test
